### ISSUE TITLE
Add support for per directory commands

### ISSUE THREAD

**Issue by cknadler** [cknadler/rcomp#28]
Currently, RComp only has support for one command per project. If you have a large amount of tests, chances are you are going to need to run different commands. 

There are two possible approaches:

First, you could put a `.rcomp` file in test folders to overwrite configuration options. This would work but would probably be very messy. 

Another option is to allow for a new set of options in the root `.rcomp` file. 

```
executable:
  - default: src/executable1
  - hashing: src/executable2 --stdout
    - bcrypt: src/executable1 --verbose
```
